name: Server

on:
  push:
    branches:
        - main
    paths:
        - backend/**

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: sh deploy.sh 
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.PROD_HOST }}
          user: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          connect_timeout: 10s
          first_ssh: |
            sh deploy.sh